# Generated by Django 5.2.1 on 2025-05-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='doctor',
        ),
        migrations.AddField(
            model_name='paciente',
            name='estado',
            field=models.CharField(default='activo', max_length=9),
        ),
    ]
