# Generated by Django 5.2.1 on 2025-05-28 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_paciente_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='id',
            new_name='idpaciente',
        ),
    ]
