# Generated by Django 5.2.1 on 2025-06-10 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_rename_id_paciente_idpaciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sintoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='idpaciente',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='sintomas',
        ),
        migrations.AddField(
            model_name='paciente',
            name='doctor',
            field=models.ManyToManyField(related_name='pacientes', to='hospital.doctor'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.CharField(max_length=100)),
                ('peso', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='hospital.doctor')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='hospital.paciente')),
                ('medicamento', models.ManyToManyField(related_name='consultas', to='hospital.medicamento')),
                ('sintoma', models.ManyToManyField(related_name='consultas', to='hospital.sintoma')),
            ],
        ),
        migrations.DeleteModel(
            name='Citas',
        ),
    ]
